### ISSUE TITLE
k8s 1.10 : Dangling pod not getting delete after migration of volume from one node to other

### ISSUE THREAD

**Issue by atotala** [hpe-storage/python-hpedockerplugin#186]
**Step to reproduce:**

**1. Create a pod(pod-1) on node(master)**
```
[root@kube-master ~]# kg pod -o wide
NAME      READY     STATUS    RESTARTS   AGE       IP          NODE
pod-1     2/2       Running   0          19s       10.32.0.2   kube-master
[root@kube-master ~]#
```

**2. Create a pod(pod-2) on node(worker2) with same pvc**
```
[root@kube-master ~]# kubectl create -f - << EOF
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: export
      mountPath: /export
  - name: minio
    image: minio/minio:latest
    args:
    - server
    - /export
    env:
    - name: MINIO_ACCESS_KEY
      value: minio
    - name: MINIO_SECRET_KEY
      value: doryspeakswhale
    ports:
    - containerPort: 9000
    volumeMounts:
    - name: export
      mountPath: /export

  volumes:
    - name: export
      persistentVolumeClaim:
        claimName: pvc-comp
  nodeSelector:
    node: worker2
EOF
pod "pod-2" created
[root@kube-master ~]#
[root@kube-master ~]#
[root@kube-master ~]# kg pod
NAME      READY     STATUS    RESTARTS   AGE
pod-1     2/2       Running   0          1m
pod-2     2/2       Running   0          1m
[root@kube-master ~]#
[root@kube-master ~]#
```

**3. Delete pod(pod-1) on node(master), pod is not getting deleted**

```
[root@kube-master ~]# kd pod pod-1
pod "pod-1" deleted
[root@kube-master ~]# kg pod
NAME      READY     STATUS        RESTARTS   AGE
pod-1     0/2       Terminating   0          4m
pod-2     2/2       Running       0          3m
[root@kube-master ~]# 
```
