### ISSUE TITLE
Reclaim policy not inherited

### ISSUE THREAD

**Issue by jeonghakw** [hpe-storage/python-hpedockerplugin#468]
After setting the Recaim Policy to Retain in Storage Class Spec for Dynamic PV as shown below, creating a PVC sets the default policy to Delete.
  Can you ensure that the policy set by Storage Class is applied to the PV? 

# kubectl describe storageclass.storage.k8s.io/thin
Name:                  thin
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           hpe.com/hpe
Parameters:            provisioning=thin
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Retain
VolumeBindingMode:     Immediate
Events:                <none>

==> ReclaimPolicy is set  "Retain"

# kubectl get sc,pv,pvc,pod,sts,deploy -o wide
NAME                               PROVISIONER   AGE
storageclass.storage.k8s.io/thin   hpe.com/hpe   2h

NAME                                                         CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                                STORAGECLASS   REASON    AGE
persistentvolume/thin-3928f3d4-13cf-11e9-86db-98f2b3ec6d34   1Gi        RWO            Delete           Bound     default/export-nginx-deployment1-1   thin                     1h
 
==> ReclaimPolicy is "Delete"

**Comment by prablr79** [comment]
@jeonghakw will address in upcoming release

**Comment by wdurairaj** [comment]
Steps to install new flexvolume binary installer (need to be done on all nodes)
```
1.	wget https://github.com/hpe-storage/python-hpedockerplugin/raw/master/dory_installer_v31 
2.	chmod u+x ./dory_installer_v31
3.	./dory_installer_v31 (type “yes” for the end user agreement, and the installation is done).
```

**Comment by virendra-sharma** [comment]
@wdurairaj @prablr79 
Verified bug in kubernetes 1.13 environment and it worked well as expected.
After setting reclaim policy in storage class as retain, it is reflecting in persistent volume status. also it is behaving as per design.

Please find below output for the same.

```
[root@cld6b12 ~]# kubectl create -f sc-import.yml
storageclass.storage.k8s.io/sc-import created
[root@cld6b12 ~]# kubectl create -f pvc-import.yml
persistentvolumeclaim/pvc-import created
[root@cld6b12 ~]# kubectl create -f pod-import.yml
pod/pod-import created


[root@cld6b12 ~]# kubectl get sc,pv,pvc,pod
NAME                                    PROVISIONER   AGE
storageclass.storage.k8s.io/sc-import   hpe.com/hpe   27s

NAME                                                              CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                STORAGECLASS   REASON   AGE
persistentvolume/sc-import-b9f3b169-5c4f-11e9-8723-10604b98ece8   35Gi       RWO            Retain           Bound    default/pvc-import   sc-import               23s

NAME                               STATUS   VOLUME                                           CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/pvc-import   Bound    sc-import-b9f3b169-5c4f-11e9-8723-10604b98ece8   35Gi       RWO            sc-import      23s

NAME             READY   STATUS    RESTARTS   AGE
pod/pod-import   1/1     Running   0          13s


[root@cld6b12 ~]# docker volume ls
DRIVER              VOLUME NAME
hpe                 sc-import-b9f3b169-5c4f-11e9-8723-10604b98ece8

[root@cld6b12 ~]# kubectl delete pod/pod-import
pod "pod-import" deleted
[root@cld6b12 ~]# kubectl delete persistentvolumeclaim/pvc-import
persistentvolumeclaim "pvc-import" deleted
[root@cld6b12 ~]# kubectl delete persistentvolume/sc-import-b9f3b169-5c4f-11e9-8723-10604b98ece8 storageclass.storage.k8s.io/sc-import
persistentvolume "sc-import-b9f3b169-5c4f-11e9-8723-10604b98ece8" deleted
storageclass.storage.k8s.io "sc-import" deleted

[root@cld6b12 ~]# kubectl get sc,pv,pvc,pod
No resources found.

[root@cld6b12 ~]# docker volume ls
DRIVER              VOLUME NAME
hpe                 sc-import-b9f3b169-5c4f-11e9-8723-10604b98ece8

[root@cld6b12 ~]# docker volume rm sc-import-b9f3b169-5c4f-11e9-8723-10604b98ece8
sc-import-b9f3b169-5c4f-11e9-8723-10604b98ece8

[root@cld6b12 ~]# docker volume ls
DRIVER              VOLUME NAME
```

YAML's used:
```
[root@cld6b12 ~]# cat sc-import.yml
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: sc-import
provisioner: hpe.com/hpe
parameters:
  name: TEST_VOLUME
reclaimPolicy: Retain


[root@cld6b12 ~]# cat pvc-import.yml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-import
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi
  storageClassName: sc-import


[root@cld6b12 ~]# cat pod-import.yml
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-import
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: export
      mountPath: /export
  restartPolicy: Always
  volumes:
  - name: export
    persistentVolumeClaim:
      claimName: pvc-import
```

Issue is resolved now, hence can close this bug as per above output.
