### ISSUE TITLE
ImportVol not working for additional backend in kubernetes

### ISSUE THREAD

**Issue by virendra-sharma** [hpe-storage/python-hpedockerplugin#492]
Unable to importVol from additional backend in kubernetes 1.13 setup. getting doryd error log as below.

Error log of doryd
============
7:19:04 provisioner.go:237: statusLogger: provision chains=0, delete chains=0, parked chains=0, ids tracked=0, connection=valid
07:19:05 class.go:75: unable to find a class named
07:19:05 claim.go:77: error getting class named  for pvc pvc-importvol. err=unable to find a class named

Steps performed
===========
1) created volume (Test_vol) in 3PAR1 array.
2) Created pv, pvc with below yml files.
3) observed volume not imported.

YAML's
=====

importvol_pv.yml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-import-volume
spec:
    capacity:
      storage: 35Gi
    accessModes:
    - ReadWriteOnce
    flexVolume:
      driver: hpe.com/hpe
      options:
        name: "IMPORTED-VOLUME"
        importVol: "Test_vol"
        backend: "3PAR1"

importvol_pvc.yml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-importvol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi

Note:- Able to import same volume through docker command. (docker volume create -d hpe --name imported_vol -o importVol=Test_vol -o backend=3PAR1).

**Comment by nilangekarss** [comment]
Can you also put the container logs for the same?

**Comment by virendra-sharma** [comment]
[container_logs.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2913452/container_logs.txt)
Please find attached container_logs.

**Comment by wdurairaj** [comment]
@virendra-sharma , I did some experimentation on this one. Seems like in static provisioning only when you do a pod mount referencing a pvc claim, then the volume is created.. 

Can you try creating a pod like this
```
sudo kubectl create -f - << EOF
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: export
      mountPath: /export
  restartPolicy: Always
  volumes:
  - name: export
    persistentVolumeClaim:
      claimName: pvc-importvol
EOF
```
