### ISSUE TITLE
pod deletion for file share goes in a terminating state after deleting the pod in OpenShift and K8S environment.

### ISSUE THREAD

**Issue by nilangekarss** [hpe-storage/python-hpedockerplugin#646]

**Comment by nilangekarss** [comment]
YAML files for pod creation:
```
[root@cssosbe04-b16 filePersona]# cat sc_sandesh_file.yml pvcfile_sandesh5.yml podfile_sandesh5.yml
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: sc-sandesh-file
provisioner: hpe.com/hpe
parameters:
  filePersona: ""
  fpg: sandesh_new_fpg

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvcfile-sandesh6
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
  storageClassName: sc-sandesh-file
---
kind: Pod
apiVersion: v1
metadata:
  name: podfile-sandesh5
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: export
      mountPath: /export
  restartPolicy: Always
  volumes:
  - name: export
    persistentVolumeClaim:
      claimName: pvcfile-sandesh5
```
