### ISSUE TITLE
snapshots in openshift

### ISSUE THREAD

**Issue by oscarnorori** [hpe-storage/python-hpedockerplugin#665]
I have a question regarding the openshift/kubernetes plugin. Beyond being able to dynamically provision volumes, we also have a need to create a snapshot of one of those volumes and then mount that snapshot in another pod. Typical use case is needing to create a pod for production investigation purposes or for testing of a new feature with production data. The documentation does not cover how to do this via the plugin. We are using openshift/kubernetes for this.

**Comment by wdurairaj** [comment]
You need to use `virtualCopyOf` parameter in storage class
Eg.

```yaml
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: sc-hpe-3par-snap
provisioner: hpe.com/hpe
parameters:
  virtualCopyOf: "vol_name_to_take_snapshot"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-hpe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: sc-hpe-3par-snap
```

Complete list of parameters are there in

https://github.com/hpe-storage/python-hpedockerplugin/blob/master/docs/usage.md#supported-storageclass-parameters
